# Generated by Django 5.1.6 on 2025-02-08 13:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9fb50a16-2158-4533-b413-9f748cf42f17'), primary_key=True, serialize=False, unique=True),
        ),
    ]
